inherit_from: .rubocop_todo.yml

inherit_gem:
  betterlint:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'spec/dummy/db/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
