inherit_from: .rubocop_todo.yml

inherit_gem:
  betterlint:
    - config/default.yml

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 8.0
  NewCops: enable
  Exclude:
    - 'spec/dummy/db/**/*'
    - 'vendor/**/*'
    - 'gemfiles/*.gemfile'
