---
version: 2.1
jobs:
  started:
    resource_class: small
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/coach-notifier/generic:v1.x
    working_directory: "~/journaled"
    steps:
    - run:
        name: notify coach of Workflow Starts
        command: notify_coach workflow_starts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  completed:
    resource_class: small
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/coach-notifier/generic:v1.x
    working_directory: "~/journaled"
    steps:
    - run:
        name: notify coach of Workflow Successes
        command: notify_coach workflow_successes
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  journaled--lint--rails_5_1_gemfile:
    resource_class: small
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5_1.gemfile
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/ruby/2.4.2:v2.x
      environment:
        GEM_SOURCE: https://rubygems.org
        RAILS_ENV: test
        RACK_ENV: test
    working_directory: "~/journaled"
    steps:
    - run:
        name: Generate git refs cache key
        command: date +%Y-%m-%d > /tmp/.git-refs-cache-key
    - restore_cache:
        keys:
        - v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
        - v2-git-refs-
    - run:
        name: Checkout code
        command: checkout
    - save_cache:
        paths: ".git"
        key: v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
    - run:
        name: run coach check
        command: |
          cd .
          coach check
    - restore_cache:
        keys:
        - v0-journaled-2.4.2-gemfiles/rails_5_1.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_1.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
        - v0-journaled-2.4.2-gemfiles/rails_5_1.gemfile-
    - run:
        name: bundle install dependencies
        command: |
          cd .
          bundle check --path vendor/bundle \
            || bundle install --clean --jobs=2 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - "./vendor/bundle"
        key: v0-journaled-2.4.2-gemfiles/rails_5_1.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_1.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
    - run:
        name: run rubocop
        command: |
          cd .
          mkdir -p /tmp/artifacts
          bundle exec rubocop --format progress \
                              --format html \
                              --out /tmp/artifacts/rubocop-report.html
    - store_artifacts:
        path: "/tmp/artifacts"
        destination: artifacts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  journaled--lint--rails_5_2_gemfile:
    resource_class: small
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5_2.gemfile
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/ruby/2.4.2:v2.x
      environment:
        GEM_SOURCE: https://rubygems.org
        RAILS_ENV: test
        RACK_ENV: test
    working_directory: "~/journaled"
    steps:
    - run:
        name: Generate git refs cache key
        command: date +%Y-%m-%d > /tmp/.git-refs-cache-key
    - restore_cache:
        keys:
        - v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
        - v2-git-refs-
    - run:
        name: Checkout code
        command: checkout
    - save_cache:
        paths: ".git"
        key: v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
    - run:
        name: run coach check
        command: |
          cd .
          coach check
    - restore_cache:
        keys:
        - v0-journaled-2.4.2-gemfiles/rails_5_2.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_2.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
        - v0-journaled-2.4.2-gemfiles/rails_5_2.gemfile-
    - run:
        name: bundle install dependencies
        command: |
          cd .
          bundle check --path vendor/bundle \
            || bundle install --clean --jobs=2 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - "./vendor/bundle"
        key: v0-journaled-2.4.2-gemfiles/rails_5_2.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_2.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
    - run:
        name: run rubocop
        command: |
          cd .
          mkdir -p /tmp/artifacts
          bundle exec rubocop --format progress \
                              --format html \
                              --out /tmp/artifacts/rubocop-report.html
    - store_artifacts:
        path: "/tmp/artifacts"
        destination: artifacts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  journaled--lint--rails_6_0_gemfile:
    resource_class: small
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_6_0.gemfile
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/ruby/2.4.2:v2.x
      environment:
        GEM_SOURCE: https://rubygems.org
        RAILS_ENV: test
        RACK_ENV: test
    working_directory: "~/journaled"
    steps:
    - run:
        name: Generate git refs cache key
        command: date +%Y-%m-%d > /tmp/.git-refs-cache-key
    - restore_cache:
        keys:
        - v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
        - v2-git-refs-
    - run:
        name: Checkout code
        command: checkout
    - save_cache:
        paths: ".git"
        key: v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
    - run:
        name: run coach check
        command: |
          cd .
          coach check
    - restore_cache:
        keys:
        - v0-journaled-2.4.2-gemfiles/rails_6_0.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_6_0.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
        - v0-journaled-2.4.2-gemfiles/rails_6_0.gemfile-
    - run:
        name: bundle install dependencies
        command: |
          cd .
          bundle check --path vendor/bundle \
            || bundle install --clean --jobs=2 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - "./vendor/bundle"
        key: v0-journaled-2.4.2-gemfiles/rails_6_0.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_6_0.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
    - run:
        name: run rubocop
        command: |
          cd .
          mkdir -p /tmp/artifacts
          bundle exec rubocop --format progress \
                              --format html \
                              --out /tmp/artifacts/rubocop-report.html
    - store_artifacts:
        path: "/tmp/artifacts"
        destination: artifacts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  journaled--test--rails_5_1_gemfile:
    resource_class: small
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5_1.gemfile
      EAGER_LOAD: true
    parallelism: 1
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/ruby/2.4.2:v2.x
      environment:
        GEM_SOURCE: https://rubygems.org
        RAILS_ENV: test
        RACK_ENV: test
    - image: circleci/postgres:9.6
      command: postgres --max_prepared_transactions=100
      environment:
        POSTGRES_USER: betterment
    working_directory: "~/journaled"
    steps:
    - run:
        name: Generate git refs cache key
        command: date +%Y-%m-%d > /tmp/.git-refs-cache-key
    - restore_cache:
        keys:
        - v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
        - v2-git-refs-
    - run:
        name: Checkout code
        command: checkout
    - save_cache:
        paths: ".git"
        key: v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
    - restore_cache:
        keys:
        - v0-journaled-2.4.2-gemfiles/rails_5_1.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_1.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
        - v0-journaled-2.4.2-gemfiles/rails_5_1.gemfile-
    - run:
        name: bundle install dependencies
        command: |
          cd .
          bundle check --path vendor/bundle \
            || bundle install --clean --jobs=2 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - "./vendor/bundle"
        key: v0-journaled-2.4.2-gemfiles/rails_5_1.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_1.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
    - run:
        name: wait for postgresql db
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: setup database
        command: |
          cd .
          bundle exec rake db:test:prepare
    - run:
        name: run rspec tests
        command: |
          cd .
          mkdir -p /tmp/artifacts
          TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
          echo "RSpec file pattern: $TEST_FILES"
          bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/artifacts/rspec.xml \
                            -- \
                            $TEST_FILES
    - run:
        name: save screenshots
        command: |
          cd .
          if [ -d spec/error_screenshots ]; then
            mv spec/error_screenshots /tmp/artifacts
          fi
          if [ -d tmp/screenshots ]; then
            mv tmp/screenshots /tmp/artifacts
          fi
        when: always
    - run:
        name: save rspec example persistence file
        command: |
          cd .
          if [ -f spec/examples.txt ]; then
            mv spec/examples.txt /tmp/artifacts
          fi
        when: always
    - run:
        name: save test logs
        command: |
          cd .
          if [ -f log/test.log ]; then
            mv log/test.log /tmp/artifacts
          fi
        when: always
    - store_test_results:
        path: "/tmp/artifacts"
    - run:
        name: upload junit file to coach
        command: upload_junit_file_to_coach /tmp/artifacts/rspec.xml
        when: on_fail
    - store_artifacts:
        path: "/tmp/artifacts"
        destination: artifacts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  journaled--test--rails_5_2_gemfile:
    resource_class: small
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5_2.gemfile
      EAGER_LOAD: true
    parallelism: 1
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/ruby/2.4.2:v2.x
      environment:
        GEM_SOURCE: https://rubygems.org
        RAILS_ENV: test
        RACK_ENV: test
    - image: circleci/postgres:9.6
      command: postgres --max_prepared_transactions=100
      environment:
        POSTGRES_USER: betterment
    working_directory: "~/journaled"
    steps:
    - run:
        name: Generate git refs cache key
        command: date +%Y-%m-%d > /tmp/.git-refs-cache-key
    - restore_cache:
        keys:
        - v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
        - v2-git-refs-
    - run:
        name: Checkout code
        command: checkout
    - save_cache:
        paths: ".git"
        key: v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
    - restore_cache:
        keys:
        - v0-journaled-2.4.2-gemfiles/rails_5_2.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_2.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
        - v0-journaled-2.4.2-gemfiles/rails_5_2.gemfile-
    - run:
        name: bundle install dependencies
        command: |
          cd .
          bundle check --path vendor/bundle \
            || bundle install --clean --jobs=2 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - "./vendor/bundle"
        key: v0-journaled-2.4.2-gemfiles/rails_5_2.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_5_2.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
    - run:
        name: wait for postgresql db
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: setup database
        command: |
          cd .
          bundle exec rake db:test:prepare
    - run:
        name: run rspec tests
        command: |
          cd .
          mkdir -p /tmp/artifacts
          TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
          echo "RSpec file pattern: $TEST_FILES"
          bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/artifacts/rspec.xml \
                            -- \
                            $TEST_FILES
    - run:
        name: save screenshots
        command: |
          cd .
          if [ -d spec/error_screenshots ]; then
            mv spec/error_screenshots /tmp/artifacts
          fi
          if [ -d tmp/screenshots ]; then
            mv tmp/screenshots /tmp/artifacts
          fi
        when: always
    - run:
        name: save rspec example persistence file
        command: |
          cd .
          if [ -f spec/examples.txt ]; then
            mv spec/examples.txt /tmp/artifacts
          fi
        when: always
    - run:
        name: save test logs
        command: |
          cd .
          if [ -f log/test.log ]; then
            mv log/test.log /tmp/artifacts
          fi
        when: always
    - store_test_results:
        path: "/tmp/artifacts"
    - run:
        name: upload junit file to coach
        command: upload_junit_file_to_coach /tmp/artifacts/rspec.xml
        when: on_fail
    - store_artifacts:
        path: "/tmp/artifacts"
        destination: artifacts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
  journaled--test--rails_6_0_gemfile:
    resource_class: small
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_6_0.gemfile
      EAGER_LOAD: true
    parallelism: 1
    docker:
    - image: 907128454492.dkr.ecr.us-east-1.amazonaws.com/betterment/ruby/2.4.2:v2.x
      environment:
        GEM_SOURCE: https://rubygems.org
        RAILS_ENV: test
        RACK_ENV: test
    - image: circleci/postgres:9.6
      command: postgres --max_prepared_transactions=100
      environment:
        POSTGRES_USER: betterment
    working_directory: "~/journaled"
    steps:
    - run:
        name: Generate git refs cache key
        command: date +%Y-%m-%d > /tmp/.git-refs-cache-key
    - restore_cache:
        keys:
        - v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
        - v2-git-refs-
    - run:
        name: Checkout code
        command: checkout
    - save_cache:
        paths: ".git"
        key: v2-git-refs-{{ checksum "/tmp/.git-refs-cache-key" }}
    - restore_cache:
        keys:
        - v0-journaled-2.4.2-gemfiles/rails_6_0.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_6_0.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
        - v0-journaled-2.4.2-gemfiles/rails_6_0.gemfile-
    - run:
        name: bundle install dependencies
        command: |
          cd .
          bundle check --path vendor/bundle \
            || bundle install --clean --jobs=2 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - "./vendor/bundle"
        key: v0-journaled-2.4.2-gemfiles/rails_6_0.gemfile-{{ checksum "./coach.yml"
          }}-{{ checksum "./gemfiles/rails_6_0.gemfile" }}-{{ checksum "./journaled.gemspec"
          }}
    - run:
        name: wait for postgresql db
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: setup database
        command: |
          cd .
          bundle exec rake db:test:prepare
    - run:
        name: run rspec tests
        command: |
          cd .
          mkdir -p /tmp/artifacts
          TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
          echo "RSpec file pattern: $TEST_FILES"
          bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/artifacts/rspec.xml \
                            -- \
                            $TEST_FILES
    - run:
        name: save screenshots
        command: |
          cd .
          if [ -d spec/error_screenshots ]; then
            mv spec/error_screenshots /tmp/artifacts
          fi
          if [ -d tmp/screenshots ]; then
            mv tmp/screenshots /tmp/artifacts
          fi
        when: always
    - run:
        name: save rspec example persistence file
        command: |
          cd .
          if [ -f spec/examples.txt ]; then
            mv spec/examples.txt /tmp/artifacts
          fi
        when: always
    - run:
        name: save test logs
        command: |
          cd .
          if [ -f log/test.log ]; then
            mv log/test.log /tmp/artifacts
          fi
        when: always
    - store_test_results:
        path: "/tmp/artifacts"
    - run:
        name: upload junit file to coach
        command: upload_junit_file_to_coach /tmp/artifacts/rspec.xml
        when: on_fail
    - store_artifacts:
        path: "/tmp/artifacts"
        destination: artifacts
    - run:
        name: notify coach of Build Failures
        command: notify_coach build_failures
        when: on_fail
workflows:
  version: 2
  all:
    jobs:
    - started:
        context: org-global
    - completed:
        context: org-global
        requires:
        - started
        - journaled--lint--rails_5_1_gemfile
        - journaled--lint--rails_5_2_gemfile
        - journaled--lint--rails_6_0_gemfile
        - journaled--test--rails_5_1_gemfile
        - journaled--test--rails_5_2_gemfile
        - journaled--test--rails_6_0_gemfile
    - journaled--lint--rails_5_1_gemfile:
        context: org-global
        requires:
        - started
    - journaled--lint--rails_5_2_gemfile:
        context: org-global
        requires:
        - started
    - journaled--lint--rails_6_0_gemfile:
        context: org-global
        requires:
        - started
    - journaled--test--rails_5_1_gemfile:
        context: org-global
        requires:
        - started
    - journaled--test--rails_5_2_gemfile:
        context: org-global
        requires:
        - started
    - journaled--test--rails_6_0_gemfile:
        context: org-global
        requires:
        - started
coach_version: 0.20.31
