# frozen_string_literal: true

class CreateJournaledEvents < ActiveRecord::Migration[7.2]
  def change
    # UUID v7 primary key (auto-generated by database using uuid_generate_v7())
    create_table :journaled_outbox_events, id: :uuid, default: -> { "uuid_generate_v7()" } do |t| # rubocop:disable Rails/CreateTableWithTimestamps
      # Event identification and data
      t.string :event_type, null: false
      t.jsonb :event_data, null: false
      t.string :partition_key, null: false
      t.string :stream_name, null: false

      t.text :failure_reason

      t.column :failed_at, :timestamptz
      t.column :created_at, :timestamptz, null: false, default: -> { "clock_timestamp()" }
    end

    # Index for querying failed events
    add_index :journaled_outbox_events, :failed_at
  end
end
